"""Reverse proxy for services published behind peers.

Same shape as :mod:`foxguard.nftables` and :mod:`foxguard.dns`: ``model`` holds
pure data, ``haproxy`` turns it into text, and the agent applies it. Nothing
here talks to a database or to the network.
"""

from .haproxy import (
    DEFAULT_ERROR_FILE,
    GROUPS_MAP_FILE,
    PEER_SET,
    PEERS_MAP_FILE,
    ProxyValidationError,
    backend_name,
    error_file,
    ipfilter_file,
    proxy_digest,
    render_conf,
    render_files,
    set_file,
    tcp_frontend_name,
    token_file,
    userlist_name,
    validate_spec,
)
from .model import (
    GEO_FILTERS,
    HTTP_ONLY_AUTH,
    HTTP_ONLY_FILTERS,
    SLUG_RE,
    UNIMPLEMENTED_FILTERS,
    AccessAction,
    AccessRule,
    Account,
    Authenticator,
    AuthKind,
    Backend,
    Exposure,
    Filter,
    FilterKind,
    PeerIdentity,
    ProxySpec,
    Scope,
    Service,
    ServiceKind,
    SourceSet,
)

__all__ = [
    "DEFAULT_ERROR_FILE",
    "GROUPS_MAP_FILE",
    "HTTP_ONLY_AUTH",
    "HTTP_ONLY_FILTERS",
    "PEERS_MAP_FILE",
    "PEER_SET",
    "SLUG_RE",
    "GEO_FILTERS",
    "UNIMPLEMENTED_FILTERS",
    "AccessAction",
    "AccessRule",
    "Account",
    "AuthKind",
    "Authenticator",
    "Backend",
    "Exposure",
    "Filter",
    "FilterKind",
    "PeerIdentity",
    "ProxySpec",
    "ProxyValidationError",
    "Scope",
    "Service",
    "ServiceKind",
    "SourceSet",
    "backend_name",
    "error_file",
    "ipfilter_file",
    "proxy_digest",
    "render_conf",
    "render_files",
    "set_file",
    "tcp_frontend_name",
    "token_file",
    "userlist_name",
    "validate_spec",
]
